# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.WelcomeWidget = QtWidgets.QWidget(Dialog)
        self.WelcomeWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.WelcomeWidget.setStyleSheet("QWidget#WelcomeWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(46, 117, 100, 255), stop:1 rgba(102, 221, 190, 255))}")
        self.WelcomeWidget.setObjectName("WelcomeWidget")
        self.label_login = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_login.setGeometry(QtCore.QRect(340, 100, 151, 81))
        self.label_login.setStyleSheet("font: 36pt \"Tahoma\";\n"
"color: rgb(229, 232, 236);\n"
"")
        self.label_login.setObjectName("label_login")
        self.label_DSP = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_DSP.setGeometry(QtCore.QRect(250, 200, 321, 50))
        self.label_DSP.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(229, 232, 236);")
        self.label_DSP.setObjectName("label_DSP")
        self.login_btn = QtWidgets.QPushButton(self.WelcomeWidget)
        self.login_btn.setGeometry(QtCore.QRect(300, 460, 231, 41))
        self.login_btn.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(229, 232, 236);\n"
"\n"
"font: 14pt \"Tahoma\";\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.EmailLine = QtWidgets.QLineEdit(self.WelcomeWidget)
        self.EmailLine.setGeometry(QtCore.QRect(300, 300, 231, 41))
        self.EmailLine.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.EmailLine.setObjectName("EmailLine")
        self.label_3 = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_3.setGeometry(QtCore.QRect(300, 270, 71, 31))
        self.label_3.setStyleSheet("font: 10pt \"Dubai\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_4.setGeometry(QtCore.QRect(300, 350, 71, 31))
        self.label_4.setStyleSheet("font: 10pt \"Dubai\";")
        self.label_4.setObjectName("label_4")
        self.PasswordLine = QtWidgets.QLineEdit(self.WelcomeWidget)
        self.PasswordLine.setGeometry(QtCore.QRect(300, 380, 231, 41))
        self.PasswordLine.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.PasswordLine.setObjectName("PasswordLine")
        self.label_invalid_line = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_invalid_line.setGeometry(QtCore.QRect(304, 425, 221, 21))
        self.label_invalid_line.setStyleSheet("font: 10pt \"MS Shell Dlg 2\"; color:red;")
        self.label_invalid_line.setText("")
        self.label_invalid_line.setObjectName("label_invalid_line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_login.setText(_translate("Dialog", "Login"))
        self.label_DSP.setText(_translate("Dialog", "Disease Symptom Prediction"))
        self.login_btn.setText(_translate("Dialog", "Log In"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "Password"))
