# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(798, 604)
        self.WelcomeWidget = QtWidgets.QWidget(Dialog)
        self.WelcomeWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.WelcomeWidget.setStyleSheet("QWidget#WelcomeWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(46, 117, 100, 255), stop:1 rgba(102, 221, 190, 255))}")
        self.WelcomeWidget.setObjectName("WelcomeWidget")
        self.label = QtWidgets.QLabel(self.WelcomeWidget)
        self.label.setGeometry(QtCore.QRect(300, 100, 211, 101))
        self.label.setStyleSheet("font: 36pt \"Tahoma\";\n"
"color: rgb(229, 232, 236);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_2.setGeometry(QtCore.QRect(280, 200, 251, 41))
        self.label_2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(229, 232, 236);")
        self.label_2.setObjectName("label_2")
        self.create_btn = QtWidgets.QPushButton(self.WelcomeWidget)
        self.create_btn.setGeometry(QtCore.QRect(300, 530, 231, 41))
        self.create_btn.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(229, 232, 236);\n"
"\n"
"font: 14pt \"Tahoma\";\n"
"")
        self.create_btn.setObjectName("create_btn")
        self.Email_line = QtWidgets.QLineEdit(self.WelcomeWidget)
        self.Email_line.setGeometry(QtCore.QRect(300, 280, 231, 41))
        self.Email_line.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Email_line.setObjectName("Email_line")
        self.Password_line = QtWidgets.QLineEdit(self.WelcomeWidget)
        self.Password_line.setGeometry(QtCore.QRect(300, 360, 231, 41))
        self.Password_line.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Password_line.setObjectName("Password_line")
        self.Password_confirm = QtWidgets.QLineEdit(self.WelcomeWidget)
        self.Password_confirm.setGeometry(QtCore.QRect(300, 440, 231, 41))
        self.Password_confirm.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Password_confirm.setObjectName("Password_confirm")
        self.label_3 = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_3.setGeometry(QtCore.QRect(300, 250, 71, 31))
        self.label_3.setStyleSheet("font: 10pt \"Dubai\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_4.setGeometry(QtCore.QRect(300, 330, 71, 31))
        self.label_4.setStyleSheet("font: 10pt \"Dubai\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_5.setGeometry(QtCore.QRect(300, 410, 131, 31))
        self.label_5.setStyleSheet("font: 10pt \"Dubai\";")
        self.label_5.setObjectName("label_5")
        self.label_invalid_line = QtWidgets.QLabel(self.WelcomeWidget)
        self.label_invalid_line.setGeometry(QtCore.QRect(300, 490, 221, 21))
        self.label_invalid_line.setStyleSheet("font: 10pt \"MS Shell Dlg 2\"; color:red;")
        self.label_invalid_line.setText("")
        self.label_invalid_line.setObjectName("label_invalid_line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign Up"))
        self.label_2.setText(_translate("Dialog", "Create a new account "))
        self.create_btn.setText(_translate("Dialog", "Create"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_5.setText(_translate("Dialog", "Confirm password"))
