# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 756)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(46, 117, 100, 255), stop:1 rgba(102, 221, 190, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 311, 61))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 14pt; /* Font size */\n"
"    font-family: \"Century Gothic\";\n"
"    background-color: none;\n"
"}\n"
"")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 311, 471))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    font-size: 11pt;\n"
"    font-family: \"Century Gothic\";\n"
"    background-color: #A2D9CE;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 469))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: #A2D9CE;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 570, 311, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #45B39D; /* Green background color */\n"
"    border: 2px solid #138D75; /* Border color */\n"
"    color: #ffffff; /* Text color */\n"
"    padding: 8px 16px; /* Padding */\n"
"    border-radius: 4px; /* Border radius */\n"
"    font-family: \"Century Gothic\";\n"
"    font-size: 14pt; /* Font size */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #73C6B6; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #16A085; /* Clicked background color */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(420, 90, 521, 471))
        self.textBrowser.setStyleSheet("background-color: transparent;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 20, 311, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 14pt; /* Font size */\n"
"    font-family: \"Century Gothic\";\n"
"    background-color: none;\n"
"}\n"
"")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 22))
        self.menubar.setStyleSheet("background-color: transparent")
        self.menubar.setObjectName("menubar")
        self.menuAccount = QtWidgets.QMenu(self.menubar)
        self.menuAccount.setObjectName("menuAccount")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuAccount.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose the sympotms you\'re experiencing"))
        self.pushButton.setText(_translate("MainWindow", "Predict"))
        self.label_2.setText(_translate("MainWindow", "Your prediction"))
        self.menuAccount.setTitle(_translate("MainWindow", "Account"))
